export const LOAD_FETCH_START = "LOAD_FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const UPDATE_FAVORITE_RECIPE = "UPDATE_FAVORITE_RECIPE";
export const RECIPES_FAILURE = "RECIPES_FAILURE";
export const RECIPES_LOAD_DELETE = "RECIPES_LOAD_DELETE";
export const RECIPES_DELETE = "RECIPES_DELETE";
